AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DomainName:
    Description: Domain name for your website (foo.example.com)
    Type: String
  AcmWildcard:
    Description: Wildcard ACM ARN us-east-1 DNS validation
    Type: String

Resources:

  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Enabled: true
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmWildcard
          SslSupportMethod: sni-only
        Origins:
          - Id: S3-Origin
            DomainName: !GetAtt RootBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        DefaultCacheBehavior:
          TargetOriginId: S3-Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: True
            Cookies:
              Forward: all
          Compress: True

  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFrontOriginAccessIdentity for Week1

  StaticWebBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Ref: RootBucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub "arn:aws:s3:::${RootBucket}/*"
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"

Outputs:
  S3WebsiteURL:
    Value: !GetAtt RootBucket.WebsiteURL
    Description: URL for website hosted on S3
  CFDistributionId:
    Value: !Ref CloudFrontDistribution
    Description: Id for CloudFront distribution
  CFDomainName:
    Value: !GetAtt [CloudFrontDistribution, DomainName]
    Description: Endpoint for Cloudfront distribution
