AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DomainName:
    Description: Domain name for your website (foo.example.com)
    Type: String
  AcmWildcard:
    Description: Wildcard ACM ARN us-east-1 DNS validation
    Type: String
Resources:
  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Enabled: true
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmWildcard
          SslSupportMethod: sni-only
        Origins:
          - Id: S3-Origin
            DomainName: !Sub "${RootBucket}.s3-website-${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: S3-Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: True
            Cookies:
              Forward: all
          Compress: True
  StaticWebBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Ref: RootBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource:
              Fn::Join: ['', ['arn:aws:s3:::', {'Ref': 'RootBucket'}, '/*']]

Outputs:
  S3WebsiteURL:
    Value: !GetAtt RootBucket.WebsiteURL
    Description: URL for website hosted on S3
  CFDistributionId:
    Value: !Ref CloudFrontDistribution
    Description: Id for CloudFront distribution
  CFDomainName:
    Value: !GetAtt [CloudFrontDistribution, DomainName]
    Description: Endpoint for Cloudfront distribution
