AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DomainName:
    Description: Domain name for your website (foo.example.com)
    Type: String
  AcmWildcard:
    Description: Wildcard ACM ARN us-east-1 DNS validation
    Type: String
Resources:
  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub "${DomainName}"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: s3_origin
          ForwardedValues:
            Headers:
              - Origin
              - Access-Control-Allow-Origin
              - Access-Control-Request-Headers
              - Access-Control-Request-Method
              - Authorization
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt RootBucket.WebsiteURL]]
            Id: s3_origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmWildcard
          SslSupportMethod: sni-only
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFront Origin Access Identity
Outputs:
  WebsiteURL:
    Value: !GetAtt RootBucket.WebsiteURL
    Description: URL for website hosted on S3
  DistributionId:
    Value: !Ref CloudFrontDistribution
    Description: Id for CloudFront distribution
  CloudfrontEndpoint:
    Value: !GetAtt [CloudFrontDistribution, DomainName]
    Description: Endpoint for Cloudfront distribution
